include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

.default-tags:
  tags: [ruby-2.7]

.bundle: &bundle
  - bundle install -j $(sysctl -n hw.ncpu)

cache:
  key: stabibot
  paths:
    - booked_events.yml

rubocop:
  extends: .default-tags
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
  before_script:
    - *bundle
  script:
    - rubocop

audit:
  extends: .default-tags
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: delayed
      start_in: 1 minute
  script:
    - gem install bundler-audit
    - bundle audit check --update

book events:
  extends: .default-tags
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  before_script:
    - *bundle
  script:
    - ruby bot.rb $MAX_ATTEMPTS
  artifacts:
    name: remote_responses
    expose_as: remote responses
    paths:
      - 'remote_responses/'
    expire_in: 1 week

